### PR TITLE
Check gpg signature on checksums file and create symlink (optionally)

### PR DESCRIPTION
**Pull request by kostyrev**
I'd like to propose those changes.

### CODE REVIEW

**Comment by lobsterdore** [comment]
Looks good, I will need to give some thought and a bit of testing though first, can you tell me why you've added all the extra flags in? I don't want add lots of extra toggles without a genuine use case.

**Comment by lobsterdore** [comment]
I mean the create_directory, manage_service and configure toggles. Also can you squash this into one meaningful commit when you get a chance?

**Comment by kostyrev** [comment]
```
fabio_configure
fabio_create_directories
```
I use those to install fabio on my desktop. I want only binary to test integrations with my code
I use `fabio_manage_service` when building AMI with packer. There's no need in enabling and starting fabio in packer.
I added `fabio_symlink` to provide backward compatibility with old version of this role.
I added `fabio_validate_certs` because sometimes if you use docker image it comes without needed certificates.

**Comment by kostyrev** [comment]
>Also can you squash this into one meaningful commit

I coud do it but there are many changes what should be the main one, what message to you propose to use?

**Comment by lobsterdore** [comment]
@kostyrev OK thanks for confirming the use cases.

For the commit squashing, just squash everything down into your first commit and then write all your changes out into a single commit message, then we can get this merged :)

**Review by lobsterdore — APPROVED** [review]
LGTM :+1:

**Comment by lobsterdore** [comment]
@kostyrev your changes are merged and published to Ansible Galaxy (v1.2.5).

**Comment by kostyrev** [comment]
thanks!

**Pull request merged**
